### ISSUE TITLE
[Bug]: panic: unaligned 64-bit atomic operation plugin crash when trying to use .snowflake/config file with encrypted rsa key and passphrase

### ISSUE THREAD

**Issue by wyattwilliamsdev** [snowflakedb/terraform-provider-snowflake#3474]
### Terraform CLI Version

1.11.2

### Terraform Provider Version

1.0.4

### Terraform Configuration

```terraform
I'm using terraform 1.11.2
and the latest snowflake terraform provider 1.0.4

I'm setting up the provider via config file on a Windows 10 Machine

Config file:

[default]
organizationname="test"
accountname="test"
user = "test_user"
role = "test_role"
warehouse = "test_wh"
authenticator = "snowflake_jwt"
PrivateKey = """-----BEGIN ENCRYPTED PRIVATE KEY-----
asdasdasdasdasdsda
asdasdasdasdasdasd
...
-----END ENCRYPTED PRIVATE KEY-----"""
PrivateKeyPassphrase = ""

terraform config:

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.82.2"
    }
    snowflake = {
      source = "snowflake-labs/snowflake"
      version = "1.0.4"
    }
  }
  required_version = ">= 1.10.0"
}

provider "snowflake" {
  profile = "default"
}
```

### Category

category:provider_config

### Expected Behavior

Expectation was to login to our snowflake instance and begin terraform some users

### Actual Behavior

I get the following crash when running 
"terraform -chdir=terraform plan -var-file=dev.tfvars"

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ConfigureProvider call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-snowflake_v1.0.4.exe plugin:

panic: unaligned 64-bit atomic operation

goroutine 25 [running]:
internal/runtime/atomic.panicUnaligned()
        internal/runtime/atomic/unaligned.go:8 +0x2b
internal/runtime/atomic.Load64(0x5d3c554)
        internal/runtime/atomic/atomic_386.s:225 +0x10
github.com/apache/arrow/go/v16/arrow/ipc.(*Reader).Release(0x5d3c548)
        github.com/apache/arrow/go/v16@v16.0.0/arrow/ipc/reader.go:151 +0x2c
github.com/snowflakedb/gosnowflake.(*arrowResultChunk).decodeArrowChunk(0x6040c24, {0x24ed668, 0x5cbdb78}, {0x5de7b00, 0x1, 0x1}, 0x0, 0x5e381e0)
        github.com/snowflakedb/gosnowflake@v1.13.0/arrow_chunk.go:53 +0x358
github.com/snowflakedb/gosnowflake.(*snowflakeChunkDownloader).start(0x58036c8)
        github.com/snowflakedb/gosnowflake@v1.13.0/chunk_downloader.go:118 +0x304
github.com/snowflakedb/gosnowflake.(*snowflakeConn).queryContextInternal(0x5f73440, {0x24ed668, 0x5cbdb60}, {0x215bd25, 0x2b}, {0x3482e20, 0x0, 0x0})
        github.com/snowflakedb/gosnowflake@v1.13.0/connection.go:449 +0x551
github.com/snowflakedb/gosnowflake.(*snowflakeConn).QueryContext(0x5f73440, {0x24ed668, 0x5cbdb60}, {0x215bd25, 0x2b}, {0x3482e20, 0x0, 0x0})
        github.com/snowflakedb/gosnowflake@v1.13.0/connection.go:384 +0x14d
github.com/luna-duclos/instrumentedsql.wrappedConn.QueryContext({{{0x24ded30, 0x2203458}, {0x24e14d0, 0x3482e20}, 0x0, 0x0}, {0x24e9d34, 0x5f73440}}, {0x24ed668, 0x5cbdb60}, ...)
        github.com/luna-duclos/instrumentedsql@v1.1.3/conn.go:212 +0x3f3
database/sql.ctxDriverQuery({0x24ed668, 0x5cbdb60}, {0x2621cb90, 0x5cf0200}, {0x0, 0x0}, {0x215bd25, 0x2b}, {0x3482e20, 0x0, ...})
        database/sql/ctxutil.go:48 +0x8d
database/sql.(*DB).queryDC.func1()
        database/sql/sql.go:1778 +0x144
database/sql.withLock({0x24e4e90, 0x59ddb60}, 0x60414d0)
        database/sql/sql.go:3566 +0x62
database/sql.(*DB).queryDC(0x5cfd368, {0x24ed668, 0x5cbdb60}, {0x0, 0x0}, 0x59ddb60, 0x5dc86a8, {0x215bd25, 0x2b}, {0x0, ...})
        database/sql/sql.go:1773 +0x1d0
database/sql.(*DB).query(0x5cfd368, {0x24ed668, 0x5cbdb60}, {0x215bd25, 0x2b}, {0x0, 0x0, 0x0}, 0x1)
        database/sql/sql.go:1756 +0xe4
database/sql.(*DB).QueryContext.func1(0x1)
        database/sql/sql.go:1734 +0x82
database/sql.(*DB).retry(0x5cfd368, 0x60415e4)
        database/sql/sql.go:1568 +0x5d
database/sql.(*DB).QueryContext(0x5cfd368, {0x24ed668, 0x5cbdb60}, {0x215bd25, 0x2b}, {0x0, 0x0, 0x0})
        database/sql/sql.go:1733 +0xa4
github.com/jmoiron/sqlx.(*DB).QueryRowxContext(0x5e3acd8, {0x24ed668, 0x5cbdb60}, {0x215bd25, 0x2b}, {0x0, 0x0, 0x0})
        github.com/jmoiron/sqlx@v1.4.0/sqlx_context.go:172 +0x5d
github.com/jmoiron/sqlx.GetContext({0x24ed668, 0x5cbdb60}, {0x24e9d1c, 0x5e3acd8}, {0x1d98b80, 0x5dc86a0}, {0x215bd25, 0x2b}, {0x0, 0x0, ...})
        github.com/jmoiron/sqlx@v1.4.0/sqlx_context.go:83 +0x5f
github.com/jmoiron/sqlx.(*DB).GetContext(...)
        github.com/jmoiron/sqlx@v1.4.0/sqlx_context.go:148
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.(*Client).queryOne(0x59de408, {0x24ed64c, 0x3482e20}, {0x1d98b80, 0x5dc86a0}, {0x215bd25, 0x2b})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/client.go:307 +0x23e
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.(*contextFunctions).CurrentAccount(0x60730e8, {0x24ed64c, 0x3482e20})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/context_functions.go:75 +0x78
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.NewClient(0x58a3908)
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/client.go:169 +0x334
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider.ConfigureProvider({0x24ed668, 0x5cbc1c8}, 0x6308fa0)
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/provider.go:557 +0x25a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).Configure(0x62c8300, {0x24ed668, 0x5cbc1c8}, 0x58bbd40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.0/helper/schema/provider.go:391 +0x214
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ConfigureProvider(0x5cec6b0, {0x24ed668, 0x5cbc0a8}, 0x5e42810)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.0/helper/schema/grpc_provider.go:647 +0x474
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ConfigureProvider({{0x2502cac, 0x5cec6b0}}, {0x24ed668, 0x5cbc0a8}, 0x5e42800)
        github.com/hashicorp/terraform-plugin-mux@v0.18.0/tf5to6server/tf5to6server.go:71 +0x14b
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ConfigureProvider(0x58af310, {0x24ed668, 0x5cafed8}, 0x5e42800)
        github.com/hashicorp/terraform-plugin-mux@v0.18.0/tf6muxserver/mux_server_ConfigureProvider.go:28 +0x155
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ConfigureProvider(0x5c7c0f0, {0x24ed668, 0x5cafc50}, 0x58bb890)
        github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov6/tf6server/server.go:559 +0x34f
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ConfigureProvider_Handler({0x20a89a0, 0x5c7c0f0}, {0x24ed668, 0x5cafc50}, 0x600db80, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:557 +0x98
google.golang.org/grpc.(*Server).processUnaryRPC(0x61f6008, {0x24ed668, 0x5c53938}, 0x58bb7a0, 0x5c53908, 0x3455b08, 0x0)
        google.golang.org/grpc@v1.69.4/server.go:1392 +0x1007
google.golang.org/grpc.(*Server).handleStream(0x61f6008, {0x24ef1d4, 0x59e1688}, 0x58bb7a0)
        google.golang.org/grpc@v1.69.4/server.go:1802 +0xe24
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.69.4/server.go:1030 +0x8a
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 23
        google.golang.org/grpc@v1.69.4/server.go:1041 +0x12f

Error: The terraform-provider-snowflake_v1.0.4.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1.) Install latest snowflake module 1.0.4
2.) Set up a provider config in .snowflake/config on a Windows 10 machine
3.) Set up config with related encrypted key + passphrase, with correct key values, these were created via openssl genrsa commands for a 2048 bit key, the format of the key has no CR's, just LFs for the ending
https://docs.snowflake.com/en/user-guide/key-pair-auth

4.) Run terraform plan

### How much impact is this issue causing?

Low

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment]
Hi @wyattwilliamsdev 👋 

This panic comes from [Apache Arrow library](https://github.com/apache/arrow) used by [Snowflake Go driver](https://github.com/snowflakedb/gosnowflake). It seems like this is caused by improper handling of atomic values on 32-bit platforms (https://github.com/apache/arrow/issues/43186). This has been fixed in https://github.com/apache/arrow/pull/43206 and released in v18. 

We need to bump the driver on our side (`v1.13.0` to `1.13.1`, see [release notes](https://docs.snowflake.com/en/release-notes/clients-drivers/golang-2025#version-1-13-1-march-05-2025)).

**Comment by sfc-gh-jcieslak** [comment]
Hey @wyattwilliamsdev @dma092 
We bumped the driver version to the latest version of the provider (v1.0.5). Please, try to bump and let us know if the issue persists.

**Comment by dma092** [comment]
Actually, I had the bug with v1.0.5. Weird enough the version in the master branch is working in dev mode.

**Comment by sfc-gh-jmichalak** [comment]
Hi @dma092 @wyattwilliamsdev  👋 

We've just released v1.1.0 ([release](https://github.com/snowflakedb/terraform-provider-snowflake/releases/tag/v1.1.0), [migration guide](https://github.com/snowflakedb/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#v105--v110)). We bumped Go driver to v1.13.1 ([driver release notes](https://docs.snowflake.com/en/release-notes/clients-drivers/golang-2025#version-1-13-1-march-05-2025)). 

Please upgrade to this version and let us know if it works for you.

**Comment by dma092** [comment]
Hello @sfc-gh-jcieslak , thanks. It is still not available at terraform's registry.

**Comment by sfc-gh-jmichalak** [comment]
It's available in the new [snowflakedb namespace](https://registry.terraform.io/providers/snowflakedb/snowflake/1.1.0). For more details, read our [migration instructions](https://github.com/snowflakedb/terraform-provider-snowflake/blob/main/SNOWFLAKEDB_MIGRATION.md). 

This has been announced in our [roadmap](https://github.com/snowflakedb/terraform-provider-snowflake/blob/main/ROADMAP.md#24032025-snowflakedb-migration).

**Comment by rdewolfe** [comment]
Just had the same issue in v1.1.0 

```Stack trace from the terraform-provider-snowflake_v1.1.0.exe plugin:

panic: unaligned 64-bit atomic operation

goroutine 46 [running]:
internal/runtime/atomic.panicUnaligned()
        internal/runtime/atomic/unaligned.go:8 +0x2b
internal/runtime/atomic.Load64(0x4c63894)
        internal/runtime/atomic/atomic_386.s:225 +0x10
github.com/apache/arrow-go/v18/arrow/ipc.(*Reader).Release(0x4c63888)
        github.com/apache/arrow-go/v18@v18.2.0/arrow/ipc/reader.go:151 +0x2c
github.com/snowflakedb/gosnowflake.(*arrowResultChunk).decodeArrowChunk(0x4c6ce2c, {0x2eeea70, 0x4e0c0d8}, {0x4b7a300, 0x1, 0x1}, 0x0, 0x4ba7de0)
        github.com/snowflakedb/gosnowflake@v1.13.1/arrow_chunk.go:53 +0x358
github.com/snowflakedb/gosnowflake.(*snowflakeChunkDownloader).start(0x4574758)
        github.com/snowflakedb/gosnowflake@v1.13.1/chunk_downloader.go:118 +0x304
github.com/snowflakedb/gosnowflake.(*snowflakeConn).queryContextInternal(0x47f3b30, {0x2eeea70, 0x4e0c0c0}, {0x2b4fce4, 0x2b}, {0x3e81e80, 0x0, 0x0})
        github.com/snowflakedb/gosnowflake@v1.13.1/connection.go:450 +0x56f
github.com/snowflakedb/gosnowflake.(*snowflakeConn).QueryContext(0x47f3b30, {0x2eeea70, 0x4e0c0c0}, {0x2b4fce4, 0x2b}, {0x3e81e80, 0x0, 0x0})
        github.com/snowflakedb/gosnowflake@v1.13.1/connection.go:385 +0x14d
database/sql.ctxDriverQuery({0x2eeea70, 0x4e0c0c0}, {0x24f34800, 0x47f3b30}, {0x0, 0x0}, {0x2b4fce4, 0x2b}, {0x3e81e80, 0x0, ...})
        database/sql/ctxutil.go:48 +0x8d
database/sql.(*DB).queryDC.func1()
        database/sql/sql.go:1778 +0x144
database/sql.withLock({0x2ee5fe0, 0x46105a0}, 0x4c6d578)
        database/sql/sql.go:3566 +0x62
database/sql.(*DB).queryDC(0x498b408, {0x2eeea70, 0x4e0c0c0}, {0x0, 0x0}, 0x46105a0, 0x4d80908, {0x2b4fce4, 0x2b}, {0x0, ...})
        database/sql/sql.go:1773 +0x1d0
database/sql.(*DB).query(0x498b408, {0x2eeea70, 0x4e0c0c0}, {0x2b4fce4, 0x2b}, {0x0, 0x0, 0x0}, 0x1)
        database/sql/sql.go:1756 +0xe4
database/sql.(*DB).QueryContext.func1(0x1)
        database/sql/sql.go:1734 +0x82
database/sql.(*DB).retry(0x498b408, 0x4c6d68c)
        database/sql/sql.go:1568 +0x5d
database/sql.(*DB).QueryContext(0x498b408, {0x2eeea70, 0x4e0c0c0}, {0x2b4fce4, 0x2b}, {0x0, 0x0, 0x0})
        database/sql/sql.go:1733 +0xa4
github.com/jmoiron/sqlx.(*DB).QueryRowxContext(0x4e0c708, {0x2eeea70, 0x4e0c0c0}, {0x2b4fce4, 0x2b}, {0x0, 0x0, 0x0})
        github.com/jmoiron/sqlx@v1.4.0/sqlx_context.go:172 +0x5d
github.com/jmoiron/sqlx.GetContext({0x2eeea70, 0x4e0c0c0}, {0x2eeb13c, 0x4e0c708}, {0x2789f00, 0x4d80900}, {0x2b4fce4, 0x2b}, {0x0, 0x0, ...})
        github.com/jmoiron/sqlx@v1.4.0/sqlx_context.go:83 +0x5f
github.com/jmoiron/sqlx.(*DB).GetContext(...)
        github.com/jmoiron/sqlx@v1.4.0/sqlx_context.go:148
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.(*Client).queryOne(0x4432208, {0x2eeea54, 0x3e81e80}, {0x2789f00, 0x4d80900}, {0x2b4fce4, 0x2b})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/client.go:270 +0x1a8
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.(*contextFunctions).CurrentAccount(0x49c3a30, {0x2eeea54, 0x3e81e80})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/context_functions.go:75 +0x78
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.NewClient(0x44b8288)
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/client.go:138 +0x2a2
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider.ConfigureProvider({0x2eeea70, 0x45f8558}, 0x483aa50)
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/provider.go:562 +0x186
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).Configure(0x49bc840, {0x2eeea70, 0x45f8558}, 0x47f2120)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/provider.go:391 +0x214
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ConfigureProvider(0x46e6370, {0x2eeea70, 0x45f83c0}, 0x476a9b0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/grpc_provider.go:647 +0x474
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ConfigureProvider({{0x2f0424c, 0x46e6370}}, {0x2eeea70, 0x45f83c0}, 0x476a9a0)
        github.com/hashicorp/terraform-plugin-mux@v0.18.0/tf5to6server/tf5to6server.go:71 +0x14b
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ConfigureProvider(0x445cb40, {0x2eeea70, 0x45f8300}, 0x476a9a0)
        github.com/hashicorp/terraform-plugin-mux@v0.18.0/tf6muxserver/mux_server_ConfigureProvider.go:28 +0x155
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ConfigureProvider(0x455f450, {0x2eeea70, 0x45f8078}, 0x46e1c80)
        github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov6/tf6server/server.go:559 +0x34f
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ConfigureProvider_Handler({0x2a9a660, 0x455f450}, {0x2eeea70, 0x45f8078}, 0x4c14040, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:557 +0x98
google.golang.org/grpc.(*Server).processUnaryRPC(0x44b83c8, {0x2eeea70, 0x44ee018}, 0x46e1b30, 0x46efa70, 0x3e54dc8, 0x0)
        google.golang.org/grpc@v1.71.1/server.go:1405 +0x1071
google.golang.org/grpc.(*Server).handleStream(0x44b83c8, {0x2ef0544, 0x49047e8}, 0x46e1b30)
        google.golang.org/grpc@v1.71.1/server.go:1815 +0xe24
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.71.1/server.go:1035 +0x8a
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 9
        google.golang.org/grpc@v1.71.1/server.go:1046 +0x12f

Error: The terraform-provider-snowflake_v1.1.0.exe plugin crashed!`

**Comment by sfc-gh-jmichalak** [comment]
Hi @rdewolfe 👋 

What platform are you running Terraform on? Please check with `terraform version`.

If you're running on a 32-bit platform, consider upgrading to a 64-bit platform. The Go driver does not guarantee working on  32-bit platforms. We bumped the Go driver to v1.13.1, which upgraded Arrow to v18. This error seemed to be fixed in v18 (see [issue](https://github.com/apache/arrow/issues/43186)). However, it looks like this problem has not been solved entirely for 32-bit platforms ([Go issue](https://github.com/golang/go/issues/36606), [Arrow issue](https://github.com/apache/arrow-go/issues/32)) and we don't have a workaround, other than changing a platform.

**Comment by rdewolfe** [comment]
@sfc-gh-jmichalak thanks for your response, switching to AMD64 from 386 worked perfectly!
